hydra:
  run:
    dir: './outputs/${task_name}/${now:%Y-%m-%d_%H-%M-%S}'

task_name: 'Stage1'

# path
data_path: './database'
output_path: './outputs/${task_name}/${now:%Y-%m-%d_%H-%M-%S}'

# model
protein_model_name: null # Stage0 model
protein_model_fixed: False
text_model_name: 'TinyLlama/TinyLlama-1.1B-Chat-v1.0'
text_model_fixed: False
text_model_moe: False

# dataset
dataset: 'stage1'
max_length: 1024
drop_structure_rate: 0.15
sequence_only: False

# train
lr: 1e-4
lr_ratio: 0.1
fp16: True
batch_size: 2
num_epochs: 4
weight_decay: 0.0
warmup_ratio: 0.03

protein_token: '<protein>'

# task
task: 'PITStage1PretrainTask'

deepspeed: './zero3_offload.json'